### ISSUE TITLE
Trouble with PayPal in mobile terminal

### ISSUE THREAD

**Issue by kalina559** [Nets-mobile-acceptance/Netaxept-Android-SDK#72]
Hi,

I have some problems implementing the PayPal flow in an Android app, namely Pia-SDK keeps crashing when I try to use PayPal in app.
I managed to make it work in our webshop (the money was successfully captured on PayPal merchant account), so I don't think it's a problem with setting up the PayPal account or making the Register call.

This is the call I'm making to register the app payment:
https://test.epayment.nets.eu/Netaxept/Register.aspx?token=REDACTED&serviceType=B&customerCountry=DK&redirectUrl=http%3A%2F%2Flocalhost%2Fdummy.htm&paymentMethodActionList=%5B{"PaymentMethod" %3A "PayPal"%2C "Fee" %3A 0}%5D&customerNumber=77359&transactionReconRef=1704699&orderNumber=1704699&currencyCode=DKK&amount=1300&merchantId=REDACTED

Then in my app I'm running
`PiaSDK.getInstance().startPayPalProcess(this, bundle, createHandler())
` (createHandler() is our custom method)
To compare, the currently working solution looks almost exactly the same, but with this line instead:
`PiaSDK.getInstance().start(this, bundle, createHandler())
`
After running startPayPalProcess() I'm redirected to the terminal and I see this for a couple of seconds:
![image](https://user-images.githubusercontent.com/49282488/212498445-e4dfe4e5-851d-42af-a28b-49f5fb3a8b90.png)

Then the app crashes completely with this error in the logs:
```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter terminalRequestError
        at eu.nets.pia.PayPalError$TerminalRequest.<init>(Unknown Source:3)
        at eu.nets.pia.ui.webview.PayPalActivity$a.run(:2)
        at android.app.Activity.runOnUiThread(Activity.java:7489)
        at eu.nets.pia.ui.webview.PayPalActivity.a(Unknown Source:5)
        at a.a.a.d.h.b$a.run(Unknown Source:53)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8741)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

The SDK code is obfuscated so I'm not sure what's happening there, but I tried debugging it and it seems like the error is coming from PayPalActivity.class, specifically the line with a breakpoint:
![image](https://user-images.githubusercontent.com/49282488/212497846-f5b079d0-31e8-4964-94f8-20091aeec5b2.png)

Instead of Status.SUCCESS I get this.a.getStatus() == Status.THREEDSECURE.

Could you help me find what I'm doing wrong?

**Comment by Miss-PiA** [comment]
Hi @kalina559 ,
We are regret about this inconvenience. We are working on this issue and update you soon.

Thanks,

**Comment by kalina559** [comment]
Hi,

Has there been any progress on this issue?

**Comment by kalina559** [comment]
Hi,

When can the hotfix release be expected?

**Comment by Miss-PiA** [comment]
Hi @kalina559 
Can you please check if your issue has been resolved in v2.7.1 release of the SDK?

**Comment by kalina559** [comment]
Hi, unfortunately it didn't help, I'm still getting the same error when I'm using the the deprecated `PiaSDK.getInstance().startPayPalProcess(this, bundle, createHandler())`

I tried following the approach show in your documentation and used
`PiaSDK.startPayPalPayment(payPalActivityLauncher, merchantInfo, payPalPaymentRegistration)`
but now I'm getting this:
![image](https://user-images.githubusercontent.com/49282488/222479400-15f92e88-9fd3-4ad4-b489-873f1cd99015.png)


Here's my code, maybe you could point me towards what I'm doing wrong:

```
private val payPalActivityLauncher: ActivityResultLauncher<PayPalActivityLauncherInput> = registerForActivityResult(
		PayPalActivityResultContract(),
		this::transactionCompleteResult
	)

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setUpSDKLanguage()
        try {
            val merchantInfo: android.util.Pair<String, PiaSDK.Environment> = android.util.Pair("redacted", PiaSDK.Environment.TEST)

            val payPalPaymentRegistration: PayPalPaymentRegistration =
                object : PayPalPaymentRegistration {
                    override fun registerPayment(callbackWithTransaction: TransactionCallback) {
                        object : Thread() {
                            override fun run() {
                                // Make a paypal registration request with your backend
                                //to retrieve a transactionID and redirectURL.

                                val subscription = presenter.onSynchronousPayment()

                                // Callback with `transactionID` and `redirectURL` obtained from your merchant backend
                                callbackWithTransaction.successWithTransactionIDAndRedirectURL(
                                    subscription.netaxeptsTicket,
                                    Uri.parse(Constant.Uri.URI_NETAXEPT_ROLLBACK)
                                )

                                // If registration request failed with your backend, callback the SDK with the error.
                                callbackWithTransaction.failureWithError(null)
                            }
                        }.start()
                    }
                }

            PiaSDK.startPayPalPayment(payPalActivityLauncher, merchantInfo, payPalPaymentRegistration)
        } catch (cause: IllegalStateException) {
            exitScreenWithError(null)
        }
    }

private fun transactionCompleteResult(result: ProcessResult<*>) {
        when (result) {
            is ProcessResult.Success -> {
                presenter.onPaymentSuccess()
            }
            is ProcessResult.Failure -> {
                setResult(Activity.RESULT_CANCELED) // TODO change
                finish()
            }
            is ProcessResult.Cancellation -> {
                setResult(Activity.RESULT_CANCELED)
                finish()
            }
        }
    }
```

The call to our backend works without any problems, the issue happens after PiaSDK consumes the generated transactionId and tries to start the terminal.

**Comment by Miss-PiA** [comment]
Hi @kalina559 

You are facing this issue only on test environment? 
And it working fine on production environment, right?

**Comment by kalina559** [comment]
I'm currently investigating how to implement PayPal into our app so I haven't even tried using it in production environment.

**Comment by kalina559** [comment]
Great, thanks for the update :)

**Comment by Miss-PiA** [comment]
Hi @kalina559  can you please check now, if it is working for you or not? Backend team has fixed the issue

**Comment by kalina559** [comment]
Hi,

Now it's working! Thank you very much for the help :)

**Comment by Miss-PiA** [comment]
Great to hear that
